# Generated by Django 3.0.8 on 2022-05-10 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('password', models.CharField(max_length=20, verbose_name='PASSWORD')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='계정 생성일')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('interior', models.TextField(default='')),
                ('job', models.CharField(default='', max_length=32, verbose_name='직종')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='interior',
            fields=[
                ('interior_name', models.CharField(max_length=30, unique=True, verbose_name='인테리어 제목')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='공사 시작일')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='공사 종료일')),
                ('address', models.CharField(max_length=30, unique=True, verbose_name='인테리어 제목')),
                ('job', models.CharField(default='', max_length=32, verbose_name='직종')),
            ],
            options={
                'verbose_name': 'interior',
                'verbose_name_plural': 'interior',
                'db_table': 'interior',
            },
        ),
    ]
