# Generated by Django 3.2.13 on 2022-05-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaeum_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interior',
            name='user_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='user_id'),
        ),
    ]
