# Generated by Django 3.2.13 on 2022-05-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaeum_app', '0002_alter_interior_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interior',
            name='user_id',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='user_id'),
        ),
    ]
