# Generated by Django 3.2.13 on 2022-05-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaeum_app', '0003_alter_interior_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interior',
            name='address',
            field=models.CharField(max_length=30, unique=True, verbose_name='인테리어 주소'),
        ),
        migrations.AlterField(
            model_name='interior',
            name='user_id',
            field=models.CharField(max_length=32, null=True, verbose_name='user_id'),
        ),
    ]
