# Generated by Django 3.2.13 on 2022-05-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaeum_app', '0004_auto_20220521_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interior',
            name='address',
            field=models.CharField(max_length=30, verbose_name='인테리어 주소'),
        ),
        migrations.AlterField(
            model_name='interior',
            name='interior_name',
            field=models.CharField(max_length=30, verbose_name='인테리어 제목'),
        ),
    ]
