# Generated by Django 3.2.13 on 2022-05-21 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chaeum_app', '0006_auto_20220521_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interior',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='공사 종료일'),
        ),
        migrations.AlterField(
            model_name='interior',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='공사 시작일'),
        ),
    ]
